# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 07:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160813_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('nuts', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
