# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 08:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nuts',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
